name: tests

on: [push, pull_request]

env:
  PYTHONHASHSEED: 1042466059
  # plone.i18n has bad IROs.
  # ZOPE_INTERFACE_STRICT_IRO: 1
  ZOPE_INTERFACE_WARN_BAD_IRO: 1


jobs:
  test:
    strategy:
      matrix:
        python-version: ["pypy-3.10", "3.10", "3.11", "3.12", "3.13"]
        extras:
          - "[test,docs]"
        include:
          - python-version: "3.13"
            extras: "[test,docs,plone]"

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'setup.py'
    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U coverage
        python -m pip install -U -e ".${{ matrix.extras }}"
    - name: Test
      run: |
        coverage run -m zope.testrunner --test-path=src  --auto-color --auto-progress
        coverage run -a -m sphinx -b doctest -d docs/_build/doctrees docs docs/_build/doctests
        coverage combine || true
        coverage report -i || true
    - name: Lint
      if: matrix.python-version == '3.12'
      run: |
        python -m pip install -U pylint
        pylint src
    - name: Submit to Coveralls
      # This is a container action, which only runs on Linux.
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
